#ifndef COMPHY_H
#define COMPHY_H

// here we define the desired versions of interfaces

#ifndef COMPHY_TEMP_DIR
#define COMPHY_TEMP_DIR "/tmp/comphy"
#endif

#ifndef COMPHY_LOG_FILE
#define COMPHY_LOG_FILE COMPHY_TEMP_DIR "/logs"
#endif

#ifndef COMPHYCTL_SOCKET
#define COMPHYCTL_SOCKET COMPHY_TEMP_DIR "/ctl"
#endif

#ifndef COMPHY_XDG_SHELL_VERSION
#define COMPHY_XDG_SHELL_VERSION (6)
#endif

#ifndef COMPHY_LAYER_SHELL_VERSION
#define COMPHY_LAYER_SHELL_VERSION (4)
#endif

#ifndef COMPHY_PRESENTATION_VERSION
#define COMPHY_PRESENTATION_VERSION (2)
#endif

#ifndef COMPHY_FRACTIONAL_SCALE_VERSION
#define COMPHY_FRACTIONAL_SCALE_VERSION (1)
#endif

#ifndef COMPHY_CURSOR_SHAPE_VERSION
#define COMPHY_CURSOR_SHAPE_VERSION (2)
#endif

#ifndef COMPHY_TRANSACTION_TIME_OUT_MS
#define COMPHY_TRANSACTION_TIME_OUT_MS (200)
#endif

#endif
